/* Generated by Yosys 0.53 (git sha1 53c22ab7c, x86_64-conda-linux-gnu-c++ 11.2.0 -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -fdebug-prefix-map=/home/runner/work/conda-opensource-eda/conda-opensource-eda/workdir/conda-env/conda-bld/yosys_1750643350956/work=/usr/local/src/conda/yosys-0.53_0_g53c22ab7c -fdebug-prefix-map=/home/pvc/conda-gf180mcu-env/envs/gf180mcu-env=/usr/local/src/conda-prefix -fPIC -O3) */

(* src = "RTL/ring_osc2x13.v:22.1-79.10" *)
module delay_stage(in, trim, out);
  (* src = "RTL/ring_osc2x13.v:27.10-27.12" *)
  wire d0;
  (* src = "RTL/ring_osc2x13.v:27.14-27.16" *)
  wire d1;
  (* src = "RTL/ring_osc2x13.v:27.18-27.20" *)
  wire d2;
  (* src = "RTL/ring_osc2x13.v:23.11-23.13" *)
  input in;
  wire in;
  (* src = "RTL/ring_osc2x13.v:25.12-25.15" *)
  output out;
  wire out;
  (* src = "RTL/ring_osc2x13.v:24.17-24.21" *)
  input [1:0] trim;
  wire [1:0] trim;
  (* src = "RTL/ring_osc2x13.v:28.10-28.16" *)
  wire trim0b;
  (* src = "RTL/ring_osc2x13.v:28.18-28.24" *)
  wire trim1b;
  (* src = "RTL/ring_osc2x13.v:27.22-27.24" *)
  wire ts;
  (* module_not_derived = 32'd1 *)
  (* src = "RTL/ring_osc2x13.v:40.39-43.6" *)
  gf180mcu_fd_sc_mcu7t5v0__clkbuf_2 delaybuf0 (
    .I(in),
    .Z(ts)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "RTL/ring_osc2x13.v:45.39-48.6" *)
  gf180mcu_fd_sc_mcu7t5v0__clkbuf_1 delaybuf1 (
    .I(ts),
    .Z(d0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "RTL/ring_osc2x13.v:67.37-71.6" *)
  gf180mcu_fd_sc_mcu7t5v0__invz_2 delayen0 (
    .EN(trim[0]),
    .I(d2),
    .ZN(out)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "RTL/ring_osc2x13.v:50.37-54.6" *)
  gf180mcu_fd_sc_mcu7t5v0__invz_2 delayen1 (
    .EN(trim[1]),
    .I(d0),
    .ZN(d1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "RTL/ring_osc2x13.v:73.37-77.6" *)
  gf180mcu_fd_sc_mcu7t5v0__invz_8 delayenb0 (
    .EN(trim0b),
    .I(ts),
    .ZN(out)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "RTL/ring_osc2x13.v:56.37-60.6" *)
  gf180mcu_fd_sc_mcu7t5v0__invz_4 delayenb1 (
    .EN(trim1b),
    .I(ts),
    .ZN(d1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "RTL/ring_osc2x13.v:62.39-65.6" *)
  gf180mcu_fd_sc_mcu7t5v0__clkinv_2 delayint0 (
    .I(d1),
    .ZN(d2)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "RTL/ring_osc2x13.v:30.36-33.6" *)
  gf180mcu_fd_sc_mcu7t5v0__inv_1 trim0bar (
    .I(trim[0]),
    .ZN(trim0b)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "RTL/ring_osc2x13.v:35.36-38.6" *)
  gf180mcu_fd_sc_mcu7t5v0__inv_1 trim1bar (
    .I(trim[1]),
    .ZN(trim1b)
  );
endmodule

(* top =  1  *)
(* src = "RTL/digital_pll.v:25.1-72.10" *)
module pll(resetb, enable, osc, clockp, div, dco, ext_trim);
  (* src = "RTL/digital_pll.v:48.11-48.17" *)
  wire _000_;
  (* src = "RTL/digital_pll.v:41.13-41.16" *)
  wire _001_;
  (* src = "RTL/digital_pll.v:38.12-38.18" *)
  wire _002_;
  (* src = "RTL/digital_pll.v:42.18-42.26" *)
  wire _003_;
  (* src = "RTL/digital_pll.v:42.18-42.26" *)
  wire _004_;
  (* src = "RTL/digital_pll.v:42.18-42.26" *)
  wire _005_;
  (* src = "RTL/digital_pll.v:42.18-42.26" *)
  wire _006_;
  (* src = "RTL/digital_pll.v:42.18-42.26" *)
  wire _007_;
  (* src = "RTL/digital_pll.v:42.18-42.26" *)
  wire _008_;
  (* src = "RTL/digital_pll.v:42.18-42.26" *)
  wire _009_;
  (* src = "RTL/digital_pll.v:42.18-42.26" *)
  wire _010_;
  (* src = "RTL/digital_pll.v:42.18-42.26" *)
  wire _011_;
  (* src = "RTL/digital_pll.v:42.18-42.26" *)
  wire _012_;
  (* src = "RTL/digital_pll.v:42.18-42.26" *)
  wire _013_;
  (* src = "RTL/digital_pll.v:42.18-42.26" *)
  wire _014_;
  (* src = "RTL/digital_pll.v:42.18-42.26" *)
  wire _015_;
  (* src = "RTL/digital_pll.v:42.18-42.26" *)
  wire _016_;
  (* src = "RTL/digital_pll.v:42.18-42.26" *)
  wire _017_;
  (* src = "RTL/digital_pll.v:42.18-42.26" *)
  wire _018_;
  (* src = "RTL/digital_pll.v:42.18-42.26" *)
  wire _019_;
  (* src = "RTL/digital_pll.v:42.18-42.26" *)
  wire _020_;
  (* src = "RTL/digital_pll.v:42.18-42.26" *)
  wire _021_;
  (* src = "RTL/digital_pll.v:42.18-42.26" *)
  wire _022_;
  (* src = "RTL/digital_pll.v:42.18-42.26" *)
  wire _023_;
  (* src = "RTL/digital_pll.v:42.18-42.26" *)
  wire _024_;
  (* src = "RTL/digital_pll.v:42.18-42.26" *)
  wire _025_;
  (* src = "RTL/digital_pll.v:42.18-42.26" *)
  wire _026_;
  (* src = "RTL/digital_pll.v:42.18-42.26" *)
  wire _027_;
  (* src = "RTL/digital_pll.v:42.18-42.26" *)
  wire _028_;
  (* src = "RTL/digital_pll.v:49.11-49.17" *)
  wire _029_;
  (* src = "RTL/digital_pll.v:46.18-46.23" *)
  wire _030_;
  (* src = "RTL/digital_pll.v:46.18-46.23" *)
  wire _031_;
  (* src = "RTL/digital_pll.v:46.18-46.23" *)
  wire _032_;
  (* src = "RTL/digital_pll.v:46.18-46.23" *)
  wire _033_;
  (* src = "RTL/digital_pll.v:46.18-46.23" *)
  wire _034_;
  (* src = "RTL/digital_pll.v:46.18-46.23" *)
  wire _035_;
  (* src = "RTL/digital_pll.v:46.18-46.23" *)
  wire _036_;
  (* src = "RTL/digital_pll.v:46.18-46.23" *)
  wire _037_;
  (* src = "RTL/digital_pll.v:46.18-46.23" *)
  wire _038_;
  (* src = "RTL/digital_pll.v:46.18-46.23" *)
  wire _039_;
  (* src = "RTL/digital_pll.v:46.18-46.23" *)
  wire _040_;
  (* src = "RTL/digital_pll.v:46.18-46.23" *)
  wire _041_;
  (* src = "RTL/digital_pll.v:46.18-46.23" *)
  wire _042_;
  (* src = "RTL/digital_pll.v:46.18-46.23" *)
  wire _043_;
  (* src = "RTL/digital_pll.v:46.18-46.23" *)
  wire _044_;
  (* src = "RTL/digital_pll.v:46.18-46.23" *)
  wire _045_;
  (* src = "RTL/digital_pll.v:46.18-46.23" *)
  wire _046_;
  (* src = "RTL/digital_pll.v:46.18-46.23" *)
  wire _047_;
  (* src = "RTL/digital_pll.v:46.18-46.23" *)
  wire _048_;
  (* src = "RTL/digital_pll.v:46.18-46.23" *)
  wire _049_;
  (* src = "RTL/digital_pll.v:46.18-46.23" *)
  wire _050_;
  (* src = "RTL/digital_pll.v:46.18-46.23" *)
  wire _051_;
  (* src = "RTL/digital_pll.v:46.18-46.23" *)
  wire _052_;
  (* src = "RTL/digital_pll.v:46.18-46.23" *)
  wire _053_;
  (* src = "RTL/digital_pll.v:46.18-46.23" *)
  wire _054_;
  (* src = "RTL/digital_pll.v:46.18-46.23" *)
  wire _055_;
  (* src = "RTL/digital_pll.v:47.18-47.23" *)
  wire _056_;
  (* src = "RTL/digital_pll.v:47.18-47.23" *)
  wire _057_;
  (* src = "RTL/digital_pll.v:47.18-47.23" *)
  wire _058_;
  (* src = "RTL/digital_pll.v:47.18-47.23" *)
  wire _059_;
  (* src = "RTL/digital_pll.v:47.18-47.23" *)
  wire _060_;
  (* src = "RTL/digital_pll.v:47.18-47.23" *)
  wire _061_;
  (* src = "RTL/digital_pll.v:47.18-47.23" *)
  wire _062_;
  (* src = "RTL/digital_pll.v:47.18-47.23" *)
  wire _063_;
  (* src = "RTL/digital_pll.v:47.18-47.23" *)
  wire _064_;
  (* src = "RTL/digital_pll.v:47.18-47.23" *)
  wire _065_;
  (* src = "RTL/digital_pll.v:47.18-47.23" *)
  wire _066_;
  (* src = "RTL/digital_pll.v:47.18-47.23" *)
  wire _067_;
  (* src = "RTL/digital_pll.v:47.18-47.23" *)
  wire _068_;
  (* src = "RTL/digital_pll.v:47.18-47.23" *)
  wire _069_;
  (* src = "RTL/digital_pll.v:47.18-47.23" *)
  wire _070_;
  (* src = "RTL/digital_pll.v:47.18-47.23" *)
  wire _071_;
  (* src = "RTL/digital_pll.v:47.18-47.23" *)
  wire _072_;
  (* src = "RTL/digital_pll.v:47.18-47.23" *)
  wire _073_;
  (* src = "RTL/digital_pll.v:47.18-47.23" *)
  wire _074_;
  (* src = "RTL/digital_pll.v:47.18-47.23" *)
  wire _075_;
  (* src = "RTL/digital_pll.v:47.18-47.23" *)
  wire _076_;
  (* src = "RTL/digital_pll.v:47.18-47.23" *)
  wire _077_;
  (* src = "RTL/digital_pll.v:47.18-47.23" *)
  wire _078_;
  (* src = "RTL/digital_pll.v:47.18-47.23" *)
  wire _079_;
  (* src = "RTL/digital_pll.v:47.18-47.23" *)
  wire _080_;
  (* src = "RTL/digital_pll.v:47.18-47.23" *)
  wire _081_;
  (* src = "RTL/digital_pll.v:37.12-37.18" *)
  wire _082_;
  (* src = "RTL/digital_pll.v:44.18-44.24" *)
  output [1:0] clockp;
  wire [1:0] clockp;
  (* src = "RTL/digital_pll.v:48.11-48.17" *)
  wire creset;
  (* src = "RTL/digital_pll.v:41.13-41.16" *)
  input dco;
  wire dco;
  (* src = "RTL/digital_pll.v:40.18-40.21" *)
  input [4:0] div;
  wire [4:0] div;
  (* src = "RTL/digital_pll.v:38.12-38.18" *)
  input enable;
  wire enable;
  (* src = "RTL/digital_pll.v:42.18-42.26" *)
  input [25:0] ext_trim;
  wire [25:0] ext_trim;
  (* src = "RTL/digital_pll.v:49.11-49.17" *)
  wire ireset;
  (* src = "RTL/digital_pll.v:46.18-46.23" *)
  wire [25:0] itrim;
  (* src = "RTL/digital_pll.v:39.12-39.15" *)
  input osc;
  wire osc;
  (* src = "RTL/digital_pll.v:47.18-47.23" *)
  wire [25:0] otrim;
  (* src = "RTL/digital_pll.v:37.12-37.18" *)
  input resetb;
  wire resetb;
  gf180mcu_fd_sc_mcu7t5v0__mux2_1 _083_ (
    .I0(_056_),
    .I1(_003_),
    .S(_001_),
    .Z(_030_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_1 _084_ (
    .I0(_067_),
    .I1(_014_),
    .S(_001_),
    .Z(_041_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_1 _085_ (
    .I0(_074_),
    .I1(_021_),
    .S(_001_),
    .Z(_048_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_1 _086_ (
    .I0(_075_),
    .I1(_022_),
    .S(_001_),
    .Z(_049_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_1 _087_ (
    .I0(_076_),
    .I1(_023_),
    .S(_001_),
    .Z(_050_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_1 _088_ (
    .I0(_077_),
    .I1(_024_),
    .S(_001_),
    .Z(_051_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_1 _089_ (
    .I0(_078_),
    .I1(_025_),
    .S(_001_),
    .Z(_052_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_1 _090_ (
    .I0(_079_),
    .I1(_026_),
    .S(_001_),
    .Z(_053_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_1 _091_ (
    .I0(_080_),
    .I1(_027_),
    .S(_001_),
    .Z(_054_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_1 _092_ (
    .I0(_081_),
    .I1(_028_),
    .S(_001_),
    .Z(_055_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_1 _093_ (
    .I0(_057_),
    .I1(_004_),
    .S(_001_),
    .Z(_031_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_1 _094_ (
    .I0(_058_),
    .I1(_005_),
    .S(_001_),
    .Z(_032_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_1 _095_ (
    .I0(_059_),
    .I1(_006_),
    .S(_001_),
    .Z(_033_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_1 _096_ (
    .I0(_060_),
    .I1(_007_),
    .S(_001_),
    .Z(_034_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_1 _097_ (
    .I0(_061_),
    .I1(_008_),
    .S(_001_),
    .Z(_035_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_1 _098_ (
    .I0(_062_),
    .I1(_009_),
    .S(_001_),
    .Z(_036_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_1 _099_ (
    .I0(_063_),
    .I1(_010_),
    .S(_001_),
    .Z(_037_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_1 _100_ (
    .I0(_064_),
    .I1(_011_),
    .S(_001_),
    .Z(_038_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_1 _101_ (
    .I0(_065_),
    .I1(_012_),
    .S(_001_),
    .Z(_039_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_1 _102_ (
    .I0(_066_),
    .I1(_013_),
    .S(_001_),
    .Z(_040_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_1 _103_ (
    .I0(_068_),
    .I1(_015_),
    .S(_001_),
    .Z(_042_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_1 _104_ (
    .I0(_069_),
    .I1(_016_),
    .S(_001_),
    .Z(_043_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_1 _105_ (
    .I0(_070_),
    .I1(_017_),
    .S(_001_),
    .Z(_044_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_1 _106_ (
    .I0(_071_),
    .I1(_018_),
    .S(_001_),
    .Z(_045_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_1 _107_ (
    .I0(_072_),
    .I1(_019_),
    .S(_001_),
    .Z(_046_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_1 _108_ (
    .I0(_073_),
    .I1(_020_),
    .S(_001_),
    .Z(_047_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _109_ (
    .A1(_002_),
    .A2(_082_),
    .ZN(_029_)
  );
  gf180mcu_fd_sc_mcu7t5v0__or2_1 _110_ (
    .A1(_001_),
    .A2(_029_),
    .Z(_000_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "RTL/digital_pll.v:64.20-70.6" *)
  pll_controller pll_control (
    .clock(clockp[0]),
    .div(div),
    .osc(osc),
    .reset(creset),
    .trim(otrim)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "RTL/digital_pll.v:58.14-62.6" *)
  ring_osc ringosc (
    .clockp(clockp),
    .reset(ireset),
    .trim(itrim)
  );
  assign _056_ = otrim[0];
  assign _003_ = ext_trim[0];
  assign _001_ = dco;
  assign itrim[0] = _030_;
  assign _067_ = otrim[1];
  assign _014_ = ext_trim[1];
  assign itrim[1] = _041_;
  assign _074_ = otrim[2];
  assign _021_ = ext_trim[2];
  assign itrim[2] = _048_;
  assign _075_ = otrim[3];
  assign _022_ = ext_trim[3];
  assign itrim[3] = _049_;
  assign _076_ = otrim[4];
  assign _023_ = ext_trim[4];
  assign itrim[4] = _050_;
  assign _077_ = otrim[5];
  assign _024_ = ext_trim[5];
  assign itrim[5] = _051_;
  assign _078_ = otrim[6];
  assign _025_ = ext_trim[6];
  assign itrim[6] = _052_;
  assign _079_ = otrim[7];
  assign _026_ = ext_trim[7];
  assign itrim[7] = _053_;
  assign _080_ = otrim[8];
  assign _027_ = ext_trim[8];
  assign itrim[8] = _054_;
  assign _081_ = otrim[9];
  assign _028_ = ext_trim[9];
  assign itrim[9] = _055_;
  assign _057_ = otrim[10];
  assign _004_ = ext_trim[10];
  assign itrim[10] = _031_;
  assign _058_ = otrim[11];
  assign _005_ = ext_trim[11];
  assign itrim[11] = _032_;
  assign _059_ = otrim[12];
  assign _006_ = ext_trim[12];
  assign itrim[12] = _033_;
  assign _060_ = otrim[13];
  assign _007_ = ext_trim[13];
  assign itrim[13] = _034_;
  assign _061_ = otrim[14];
  assign _008_ = ext_trim[14];
  assign itrim[14] = _035_;
  assign _062_ = otrim[15];
  assign _009_ = ext_trim[15];
  assign itrim[15] = _036_;
  assign _063_ = otrim[16];
  assign _010_ = ext_trim[16];
  assign itrim[16] = _037_;
  assign _064_ = otrim[17];
  assign _011_ = ext_trim[17];
  assign itrim[17] = _038_;
  assign _065_ = otrim[18];
  assign _012_ = ext_trim[18];
  assign itrim[18] = _039_;
  assign _066_ = otrim[19];
  assign _013_ = ext_trim[19];
  assign itrim[19] = _040_;
  assign _068_ = otrim[20];
  assign _015_ = ext_trim[20];
  assign itrim[20] = _042_;
  assign _069_ = otrim[21];
  assign _016_ = ext_trim[21];
  assign itrim[21] = _043_;
  assign _070_ = otrim[22];
  assign _017_ = ext_trim[22];
  assign itrim[22] = _044_;
  assign _071_ = otrim[23];
  assign _018_ = ext_trim[23];
  assign itrim[23] = _045_;
  assign _072_ = otrim[24];
  assign _019_ = ext_trim[24];
  assign itrim[24] = _046_;
  assign _073_ = otrim[25];
  assign _020_ = ext_trim[25];
  assign itrim[25] = _047_;
  assign _002_ = enable;
  assign _082_ = resetb;
  assign ireset = _029_;
  assign creset = _000_;
endmodule

(* src = "RTL/digital_pll_controller.v:49.1-135.10" *)
module pll_controller(reset, clock, osc, div, trim);
  (* src = "RTL/digital_pll_controller.v:100.5-133.8" *)
  wire [4:0] _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire _309_;
  wire _310_;
  wire _311_;
  wire _312_;
  wire _313_;
  wire _314_;
  wire _315_;
  wire _316_;
  wire _317_;
  wire _318_;
  wire _319_;
  wire _320_;
  wire _321_;
  wire _322_;
  wire _323_;
  wire _324_;
  wire _325_;
  wire _326_;
  wire _327_;
  wire _328_;
  wire _329_;
  wire _330_;
  wire _331_;
  wire _332_;
  wire _333_;
  wire _334_;
  wire _335_;
  wire _336_;
  wire _337_;
  wire _338_;
  wire _339_;
  wire _340_;
  wire _341_;
  wire _342_;
  wire _343_;
  wire _344_;
  wire _345_;
  wire _346_;
  wire _347_;
  wire _348_;
  wire _349_;
  wire _350_;
  wire _351_;
  wire _352_;
  wire _353_;
  wire _354_;
  wire _355_;
  wire _356_;
  wire _357_;
  wire _358_;
  wire _359_;
  wire _360_;
  wire _361_;
  wire _362_;
  wire _363_;
  wire _364_;
  wire _365_;
  wire _366_;
  wire _367_;
  wire _368_;
  wire _369_;
  wire _370_;
  wire _371_;
  wire _372_;
  wire _373_;
  wire _374_;
  wire _375_;
  wire _376_;
  wire _377_;
  wire _378_;
  wire _379_;
  wire _380_;
  wire _381_;
  wire _382_;
  wire _383_;
  wire _384_;
  wire _385_;
  wire _386_;
  wire _387_;
  wire _388_;
  wire _389_;
  wire _390_;
  wire _391_;
  wire _392_;
  wire _393_;
  wire _394_;
  wire _395_;
  wire _396_;
  wire _397_;
  wire _398_;
  wire _399_;
  wire _400_;
  wire _401_;
  wire _402_;
  wire _403_;
  wire _404_;
  wire _405_;
  wire _406_;
  wire _407_;
  wire _408_;
  wire _409_;
  wire _410_;
  wire _411_;
  wire _412_;
  wire _413_;
  wire _414_;
  wire _415_;
  wire _416_;
  wire _417_;
  wire _418_;
  wire _419_;
  wire _420_;
  wire _421_;
  wire _422_;
  wire _423_;
  wire _424_;
  wire _425_;
  wire _426_;
  wire _427_;
  wire _428_;
  wire _429_;
  wire _430_;
  wire _431_;
  wire _432_;
  wire _433_;
  wire _434_;
  wire _435_;
  wire _436_;
  wire _437_;
  wire _438_;
  wire _439_;
  wire _440_;
  wire _441_;
  wire _442_;
  wire _443_;
  wire _444_;
  wire _445_;
  wire _446_;
  wire _447_;
  wire _448_;
  wire _449_;
  wire _450_;
  wire _451_;
  wire _452_;
  wire _453_;
  wire _454_;
  wire _455_;
  wire _456_;
  wire _457_;
  wire _458_;
  wire _459_;
  wire _460_;
  wire _461_;
  wire _462_;
  wire _463_;
  wire _464_;
  wire _465_;
  wire _466_;
  wire _467_;
  wire _468_;
  wire _469_;
  wire _470_;
  wire _471_;
  wire _472_;
  wire _473_;
  wire _474_;
  wire _475_;
  wire _476_;
  wire _477_;
  wire _478_;
  wire _479_;
  wire _480_;
  wire _481_;
  wire _482_;
  wire _483_;
  wire _484_;
  wire _485_;
  wire _486_;
  wire _487_;
  wire _488_;
  wire _489_;
  wire _490_;
  wire _491_;
  wire _492_;
  wire _493_;
  wire _494_;
  wire _495_;
  wire _496_;
  wire _497_;
  wire _498_;
  wire _499_;
  wire _500_;
  wire _501_;
  (* src = "RTL/digital_pll_controller.v:60.15-60.21" *)
  wire _502_;
  (* src = "RTL/digital_pll_controller.v:60.15-60.21" *)
  wire _503_;
  (* src = "RTL/digital_pll_controller.v:60.15-60.21" *)
  wire _504_;
  (* src = "RTL/digital_pll_controller.v:60.15-60.21" *)
  wire _505_;
  (* src = "RTL/digital_pll_controller.v:60.15-60.21" *)
  wire _506_;
  (* src = "RTL/digital_pll_controller.v:61.15-61.21" *)
  wire _507_;
  (* src = "RTL/digital_pll_controller.v:61.15-61.21" *)
  wire _508_;
  (* src = "RTL/digital_pll_controller.v:61.15-61.21" *)
  wire _509_;
  (* src = "RTL/digital_pll_controller.v:61.15-61.21" *)
  wire _510_;
  (* src = "RTL/digital_pll_controller.v:61.15-61.21" *)
  wire _511_;
  (* src = "RTL/digital_pll_controller.v:53.17-53.20" *)
  wire _512_;
  (* src = "RTL/digital_pll_controller.v:53.17-53.20" *)
  wire _513_;
  (* src = "RTL/digital_pll_controller.v:53.17-53.20" *)
  wire _514_;
  (* src = "RTL/digital_pll_controller.v:53.17-53.20" *)
  wire _515_;
  (* src = "RTL/digital_pll_controller.v:53.17-53.20" *)
  wire _516_;
  wire _517_;
  wire _518_;
  wire _519_;
  wire _520_;
  wire _521_;
  wire _522_;
  wire _523_;
  wire _524_;
  wire _525_;
  wire _526_;
  wire _527_;
  wire _528_;
  wire _529_;
  wire _530_;
  wire _531_;
  wire _532_;
  wire _533_;
  wire _534_;
  wire _535_;
  wire _536_;
  wire _537_;
  wire _538_;
  wire _539_;
  wire _540_;
  wire _541_;
  wire _542_;
  wire _543_;
  wire _544_;
  wire _545_;
  wire _546_;
  wire _547_;
  wire _548_;
  wire _549_;
  wire _550_;
  wire _551_;
  wire _552_;
  wire _553_;
  wire _554_;
  wire _555_;
  wire _556_;
  wire _557_;
  wire _558_;
  wire _559_;
  wire _560_;
  wire _561_;
  wire _562_;
  wire _563_;
  wire _564_;
  wire _565_;
  wire _566_;
  wire _567_;
  wire _568_;
  wire _569_;
  wire _570_;
  wire _571_;
  wire _572_;
  wire _573_;
  wire _574_;
  wire _575_;
  wire _576_;
  wire _577_;
  wire _578_;
  wire _579_;
  wire _580_;
  wire _581_;
  wire _582_;
  wire _583_;
  wire _584_;
  wire _585_;
  wire _586_;
  wire _587_;
  wire _588_;
  wire _589_;
  wire _590_;
  wire _591_;
  wire _592_;
  wire _593_;
  wire _594_;
  wire _595_;
  wire _596_;
  wire _597_;
  wire _598_;
  wire _599_;
  wire _600_;
  wire _601_;
  wire _602_;
  wire _603_;
  wire _604_;
  wire _605_;
  wire _606_;
  wire _607_;
  wire _608_;
  wire _609_;
  wire _610_;
  wire _611_;
  wire _612_;
  wire _613_;
  wire _614_;
  wire _615_;
  wire _616_;
  wire _617_;
  wire _618_;
  wire _619_;
  wire _620_;
  wire _621_;
  wire _622_;
  wire _623_;
  wire _624_;
  wire _625_;
  wire _626_;
  wire _627_;
  wire _628_;
  wire _629_;
  wire _630_;
  wire _631_;
  wire _632_;
  wire _633_;
  wire _634_;
  wire _635_;
  wire _636_;
  wire _637_;
  wire _638_;
  wire _639_;
  wire _640_;
  wire _641_;
  wire _642_;
  wire _643_;
  wire _644_;
  wire _645_;
  wire _646_;
  wire _647_;
  wire _648_;
  wire _649_;
  wire _650_;
  wire _651_;
  wire _652_;
  wire _653_;
  wire _654_;
  wire _655_;
  wire _656_;
  wire _657_;
  wire _658_;
  wire _659_;
  wire _660_;
  wire _661_;
  wire _662_;
  wire _663_;
  wire _664_;
  (* src = "RTL/digital_pll_controller.v:57.15-57.21" *)
  wire _665_;
  (* src = "RTL/digital_pll_controller.v:57.15-57.21" *)
  wire _666_;
  (* src = "RTL/digital_pll_controller.v:58.15-58.19" *)
  wire _667_;
  (* src = "RTL/digital_pll_controller.v:58.15-58.19" *)
  wire _668_;
  (* src = "RTL/digital_pll_controller.v:58.15-58.19" *)
  wire _669_;
  (* src = "RTL/digital_pll_controller.v:50.11-50.16" *)
  wire _670_;
  (* src = "RTL/digital_pll_controller.v:54.19-54.23" *)
  wire _671_;
  (* src = "RTL/digital_pll_controller.v:54.19-54.23" *)
  wire _672_;
  (* src = "RTL/digital_pll_controller.v:54.19-54.23" *)
  wire _673_;
  (* src = "RTL/digital_pll_controller.v:54.19-54.23" *)
  wire _674_;
  (* src = "RTL/digital_pll_controller.v:54.19-54.23" *)
  wire _675_;
  (* src = "RTL/digital_pll_controller.v:54.19-54.23" *)
  wire _676_;
  (* src = "RTL/digital_pll_controller.v:54.19-54.23" *)
  wire _677_;
  (* src = "RTL/digital_pll_controller.v:54.19-54.23" *)
  wire _678_;
  (* src = "RTL/digital_pll_controller.v:54.19-54.23" *)
  wire _679_;
  (* src = "RTL/digital_pll_controller.v:54.19-54.23" *)
  wire _680_;
  (* src = "RTL/digital_pll_controller.v:54.19-54.23" *)
  wire _681_;
  (* src = "RTL/digital_pll_controller.v:54.19-54.23" *)
  wire _682_;
  (* src = "RTL/digital_pll_controller.v:54.19-54.23" *)
  wire _683_;
  (* src = "RTL/digital_pll_controller.v:54.19-54.23" *)
  wire _684_;
  (* src = "RTL/digital_pll_controller.v:54.19-54.23" *)
  wire _685_;
  (* src = "RTL/digital_pll_controller.v:54.19-54.23" *)
  wire _686_;
  (* src = "RTL/digital_pll_controller.v:54.19-54.23" *)
  wire _687_;
  (* src = "RTL/digital_pll_controller.v:54.19-54.23" *)
  wire _688_;
  (* src = "RTL/digital_pll_controller.v:54.19-54.23" *)
  wire _689_;
  (* src = "RTL/digital_pll_controller.v:54.19-54.23" *)
  wire _690_;
  (* src = "RTL/digital_pll_controller.v:54.19-54.23" *)
  wire _691_;
  (* src = "RTL/digital_pll_controller.v:54.19-54.23" *)
  wire _692_;
  (* src = "RTL/digital_pll_controller.v:54.19-54.23" *)
  wire _693_;
  (* src = "RTL/digital_pll_controller.v:54.19-54.23" *)
  wire _694_;
  (* src = "RTL/digital_pll_controller.v:54.19-54.23" *)
  wire _695_;
  (* src = "RTL/digital_pll_controller.v:54.19-54.23" *)
  wire _696_;
  (* src = "RTL/digital_pll_controller.v:62.15-62.19" *)
  wire _697_;
  (* src = "RTL/digital_pll_controller.v:62.15-62.19" *)
  wire _698_;
  (* src = "RTL/digital_pll_controller.v:62.15-62.19" *)
  wire _699_;
  (* src = "RTL/digital_pll_controller.v:62.15-62.19" *)
  wire _700_;
  (* src = "RTL/digital_pll_controller.v:62.15-62.19" *)
  wire _701_;
  (* src = "RTL/digital_pll_controller.v:62.15-62.19" *)
  wire _702_;
  (* src = "RTL/digital_pll_controller.v:62.15-62.19" *)
  wire _703_;
  (* force_downto = 32'd1 *)
  (* src = "RTL/digital_pll_controller.v:118.7-118.17|/home/pvc/conda-gf180mcu-env/envs/gf180mcu-env/bin/../share/yosys/techmap.v:270.26-270.27" *)
  (* unused_bits = "1 2 3 4 5 6" *)
  wire [6:0] _704_;
  (* force_downto = 32'd1 *)
  (* src = "RTL/digital_pll_controller.v:123.26-123.34|/home/pvc/conda-gf180mcu-env/envs/gf180mcu-env/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [6:0] _705_;
  wire _706_;
  wire _707_;
  wire _708_;
  wire _709_;
  wire _710_;
  wire _711_;
  wire _712_;
  wire _713_;
  wire _714_;
  wire _715_;
  wire _716_;
  wire _717_;
  wire _718_;
  wire _719_;
  wire _720_;
  wire _721_;
  wire _722_;
  wire _723_;
  wire _724_;
  wire _725_;
  wire _726_;
  wire _727_;
  wire _728_;
  wire _729_;
  wire _730_;
  wire _731_;
  wire _732_;
  wire _733_;
  wire _734_;
  wire _735_;
  wire _736_;
  wire _737_;
  wire _738_;
  wire _739_;
  wire _740_;
  wire _741_;
  wire _742_;
  wire _743_;
  wire _744_;
  wire _745_;
  wire _746_;
  wire _747_;
  wire _748_;
  (* src = "RTL/digital_pll_controller.v:51.11-51.16" *)
  input clock;
  wire clock;
  (* src = "RTL/digital_pll_controller.v:60.15-60.21" *)
  wire [4:0] count0;
  (* src = "RTL/digital_pll_controller.v:61.15-61.21" *)
  wire [4:0] count1;
  (* src = "RTL/digital_pll_controller.v:53.17-53.20" *)
  input [4:0] div;
  wire [4:0] div;
  (* src = "RTL/digital_pll_controller.v:52.11-52.14" *)
  input osc;
  wire osc;
  (* src = "RTL/digital_pll_controller.v:57.15-57.21" *)
  wire [2:0] oscbuf;
  (* src = "RTL/digital_pll_controller.v:58.15-58.19" *)
  wire [2:0] prep;
  (* src = "RTL/digital_pll_controller.v:50.11-50.16" *)
  input reset;
  wire reset;
  (* src = "RTL/digital_pll_controller.v:63.16-63.20" *)
  wire [4:0] tint;
  (* src = "RTL/digital_pll_controller.v:54.19-54.23" *)
  output [25:0] trim;
  wire [25:0] trim;
  (* src = "RTL/digital_pll_controller.v:62.15-62.19" *)
  wire [6:0] tval;
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _749_ (
    .I(_506_),
    .ZN(_663_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _750_ (
    .I(_703_),
    .ZN(_664_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _751_ (
    .I(_701_),
    .ZN(_517_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _752_ (
    .I(_700_),
    .ZN(_518_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _753_ (
    .I(_697_),
    .ZN(_519_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _754_ (
    .I(_516_),
    .ZN(_520_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _755_ (
    .I(_515_),
    .ZN(_521_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _756_ (
    .I(_670_),
    .ZN(_459_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _757_ (
    .A1(_665_),
    .A2(_666_),
    .Z(_522_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _758_ (
    .I(_522_),
    .ZN(_523_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_1 _759_ (
    .I0(_511_),
    .I1(_506_),
    .S(_522_),
    .Z(_501_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_1 _760_ (
    .I0(_510_),
    .I1(_505_),
    .S(_522_),
    .Z(_500_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_1 _761_ (
    .I0(_509_),
    .I1(_504_),
    .S(_522_),
    .Z(_499_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_1 _762_ (
    .I0(_508_),
    .I1(_503_),
    .S(_522_),
    .Z(_498_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_1 _763_ (
    .I0(_507_),
    .I1(_502_),
    .S(_522_),
    .Z(_497_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _764_ (
    .A1(_702_),
    .A2(_701_),
    .ZN(_524_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _765_ (
    .A1(_700_),
    .A2(_699_),
    .ZN(_525_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _766_ (
    .A1(_505_),
    .A2(_510_),
    .Z(_526_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _767_ (
    .A1(_505_),
    .A2(_510_),
    .ZN(_527_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _768_ (
    .A1(_504_),
    .A2(_509_),
    .Z(_528_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _769_ (
    .A1(_504_),
    .A2(_509_),
    .ZN(_529_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _770_ (
    .A1(_504_),
    .A2(_509_),
    .ZN(_530_)
  );
  gf180mcu_fd_sc_mcu7t5v0__or2_1 _771_ (
    .A1(_504_),
    .A2(_509_),
    .Z(_531_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _772_ (
    .A1(_503_),
    .A2(_508_),
    .Z(_532_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _773_ (
    .A1(_503_),
    .A2(_508_),
    .ZN(_533_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _774_ (
    .A1(_502_),
    .A2(_507_),
    .Z(_534_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _775_ (
    .A1(_502_),
    .A2(_507_),
    .ZN(_535_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _776_ (
    .A1(_503_),
    .A2(_508_),
    .ZN(_536_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _777_ (
    .A1(_503_),
    .A2(_508_),
    .Z(_537_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _778_ (
    .A1(_534_),
    .A2(_537_),
    .B(_532_),
    .ZN(_538_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _779_ (
    .A1(_535_),
    .A2(_536_),
    .B(_533_),
    .ZN(_539_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _780_ (
    .A1(_531_),
    .A2(_539_),
    .B(_528_),
    .ZN(_540_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _781_ (
    .A1(_530_),
    .A2(_538_),
    .B(_529_),
    .ZN(_541_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _782_ (
    .A1(_505_),
    .A2(_510_),
    .ZN(_542_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _783_ (
    .A1(_526_),
    .A2(_542_),
    .ZN(_543_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _784_ (
    .A1(_541_),
    .A2(_543_),
    .B(_526_),
    .ZN(_544_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _785_ (
    .A1(_540_),
    .A2(_542_),
    .B(_527_),
    .ZN(_545_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _786_ (
    .A1(_506_),
    .A2(_511_),
    .ZN(_546_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _787_ (
    .I(_546_),
    .ZN(_547_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _788_ (
    .A1(_506_),
    .A2(_511_),
    .ZN(_548_)
  );
  gf180mcu_fd_sc_mcu7t5v0__or2_1 _789_ (
    .A1(_506_),
    .A2(_511_),
    .Z(_549_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _790_ (
    .A1(_547_),
    .A2(_548_),
    .ZN(_550_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi211_1 _791_ (
    .A1(_541_),
    .A2(_543_),
    .B(_550_),
    .C(_526_),
    .ZN(_551_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _792_ (
    .A1(_516_),
    .A2(_551_),
    .ZN(_552_)
  );
  gf180mcu_fd_sc_mcu7t5v0__or2_1 _793_ (
    .A1(_516_),
    .A2(_551_),
    .Z(_553_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _794_ (
    .A1(_545_),
    .A2(_549_),
    .B(_547_),
    .ZN(_554_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _795_ (
    .A1(_544_),
    .A2(_548_),
    .B(_546_),
    .ZN(_555_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _796_ (
    .A1(_552_),
    .A2(_555_),
    .ZN(_556_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor3_1 _797_ (
    .A1(_504_),
    .A2(_509_),
    .A3(_538_),
    .Z(_557_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _798_ (
    .A1(_514_),
    .A2(_557_),
    .ZN(_558_)
  );
  gf180mcu_fd_sc_mcu7t5v0__or2_1 _799_ (
    .A1(_514_),
    .A2(_557_),
    .Z(_559_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _800_ (
    .A1(_541_),
    .A2(_543_),
    .Z(_560_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _801_ (
    .A1(_540_),
    .A2(_543_),
    .Z(_561_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _802_ (
    .A1(_521_),
    .A2(_560_),
    .B(_558_),
    .ZN(_562_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _803_ (
    .A1(_514_),
    .A2(_557_),
    .Z(_563_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _804_ (
    .A1(_535_),
    .A2(_537_),
    .Z(_564_)
  );
  gf180mcu_fd_sc_mcu7t5v0__or2_1 _805_ (
    .A1(_513_),
    .A2(_564_),
    .Z(_565_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xnor2_1 _806_ (
    .A1(_502_),
    .A2(_507_),
    .ZN(_566_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _807_ (
    .A1(_512_),
    .A2(_566_),
    .ZN(_567_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor3_1 _808_ (
    .A1(_513_),
    .A2(_535_),
    .A3(_537_),
    .Z(_568_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _809_ (
    .A1(_567_),
    .A2(_568_),
    .ZN(_569_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _810_ (
    .A1(_565_),
    .A2(_569_),
    .Z(_570_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _811_ (
    .A1(_514_),
    .A2(_557_),
    .B1(_565_),
    .B2(_569_),
    .ZN(_571_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi211_1 _812_ (
    .A1(_521_),
    .A2(_560_),
    .B(_571_),
    .C(_558_),
    .ZN(_572_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai221_1 _813_ (
    .A1(_515_),
    .A2(_561_),
    .B1(_563_),
    .B2(_570_),
    .C(_559_),
    .ZN(_573_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _814_ (
    .A1(_516_),
    .A2(_551_),
    .B1(_561_),
    .B2(_515_),
    .ZN(_574_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai32_1 _815_ (
    .A1(_520_),
    .A2(_545_),
    .A3(_550_),
    .B1(_560_),
    .B2(_521_),
    .ZN(_575_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _816_ (
    .A1(_573_),
    .A2(_574_),
    .ZN(_576_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi211_1 _817_ (
    .A1(_573_),
    .A2(_574_),
    .B(_552_),
    .C(_555_),
    .ZN(_577_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai211_1 _818_ (
    .A1(_572_),
    .A2(_575_),
    .B(_553_),
    .C(_554_),
    .ZN(_578_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _819_ (
    .A1(_700_),
    .A2(_699_),
    .ZN(_579_)
  );
  gf180mcu_fd_sc_mcu7t5v0__or2_1 _820_ (
    .A1(_700_),
    .A2(_699_),
    .Z(_580_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _821_ (
    .A1(_702_),
    .A2(_701_),
    .ZN(_581_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _822_ (
    .A1(_703_),
    .A2(_702_),
    .A3(_701_),
    .ZN(_582_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _823_ (
    .I(_582_),
    .ZN(_690_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _824_ (
    .A1(_579_),
    .A2(_582_),
    .ZN(_671_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _825_ (
    .A1(_512_),
    .A2(_566_),
    .ZN(_583_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _826_ (
    .A1(_563_),
    .A2(_569_),
    .A3(_583_),
    .ZN(_584_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and3_1 _827_ (
    .A1(_562_),
    .A2(_574_),
    .A3(_584_),
    .Z(_585_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _828_ (
    .A1(_562_),
    .A2(_574_),
    .A3(_584_),
    .ZN(_586_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and4_1 _829_ (
    .A1(_668_),
    .A2(_669_),
    .A3(_667_),
    .A4(_522_),
    .Z(_587_)
  );
  gf180mcu_fd_sc_mcu7t5v0__or4_1 _830_ (
    .A1(_698_),
    .A2(_697_),
    .A3(_578_),
    .A4(_671_),
    .Z(_588_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _831_ (
    .A1(_698_),
    .A2(_697_),
    .ZN(_589_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor4_1 _832_ (
    .A1(_664_),
    .A2(_524_),
    .A3(_525_),
    .A4(_589_),
    .ZN(_590_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _833_ (
    .A1(_556_),
    .A2(_585_),
    .B1(_590_),
    .B2(_578_),
    .ZN(_591_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai31_1 _834_ (
    .A1(_552_),
    .A2(_555_),
    .A3(_586_),
    .B(_578_),
    .ZN(_592_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _835_ (
    .I(_592_),
    .ZN(_593_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and3_1 _836_ (
    .A1(_587_),
    .A2(_588_),
    .A3(_591_),
    .Z(_594_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _837_ (
    .A1(_700_),
    .A2(_592_),
    .ZN(_595_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _838_ (
    .A1(_699_),
    .A2(_592_),
    .Z(_596_)
  );
  gf180mcu_fd_sc_mcu7t5v0__or2_1 _839_ (
    .A1(_699_),
    .A2(_592_),
    .Z(_597_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai211_1 _840_ (
    .A1(_576_),
    .A2(_585_),
    .B(_698_),
    .C(_556_),
    .ZN(_598_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi211_1 _841_ (
    .A1(_556_),
    .A2(_585_),
    .B(_577_),
    .C(_698_),
    .ZN(_599_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _842_ (
    .A1(_519_),
    .A2(_599_),
    .B(_598_),
    .ZN(_600_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _843_ (
    .A1(_597_),
    .A2(_600_),
    .B(_596_),
    .ZN(_601_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor4_1 _844_ (
    .A1(_518_),
    .A2(_524_),
    .A3(_592_),
    .A4(_601_),
    .ZN(_602_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _845_ (
    .A1(_700_),
    .A2(_592_),
    .ZN(_603_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _846_ (
    .A1(_595_),
    .A2(_601_),
    .B(_603_),
    .ZN(_604_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor4_1 _847_ (
    .A1(_702_),
    .A2(_701_),
    .A3(_593_),
    .A4(_604_),
    .ZN(_605_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _848_ (
    .A1(_602_),
    .A2(_605_),
    .B(_594_),
    .ZN(_606_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _849_ (
    .A1(_664_),
    .A2(_606_),
    .Z(_496_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _850_ (
    .A1(_517_),
    .A2(_593_),
    .ZN(_607_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _851_ (
    .A1(_517_),
    .A2(_593_),
    .ZN(_608_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _852_ (
    .A1(_604_),
    .A2(_608_),
    .B(_607_),
    .ZN(_609_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor3_1 _853_ (
    .A1(_702_),
    .A2(_593_),
    .A3(_609_),
    .Z(_610_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_1 _854_ (
    .I0(_702_),
    .I1(_610_),
    .S(_594_),
    .Z(_495_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor3_1 _855_ (
    .A1(_701_),
    .A2(_592_),
    .A3(_604_),
    .Z(_611_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_1 _856_ (
    .I0(_701_),
    .I1(_611_),
    .S(_594_),
    .Z(_494_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor3_1 _857_ (
    .A1(_700_),
    .A2(_593_),
    .A3(_601_),
    .Z(_612_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_1 _858_ (
    .I0(_700_),
    .I1(_612_),
    .S(_594_),
    .Z(_493_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor3_1 _859_ (
    .A1(_699_),
    .A2(_592_),
    .A3(_600_),
    .Z(_613_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_1 _860_ (
    .I0(_699_),
    .I1(_613_),
    .S(_594_),
    .Z(_492_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor3_1 _861_ (
    .A1(_698_),
    .A2(_697_),
    .A3(_592_),
    .Z(_614_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_1 _862_ (
    .I0(_698_),
    .I1(_614_),
    .S(_594_),
    .Z(_491_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _863_ (
    .A1(_697_),
    .A2(_594_),
    .Z(_490_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and3_1 _864_ (
    .A1(_504_),
    .A2(_503_),
    .A3(_502_),
    .Z(_615_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _865_ (
    .A1(_505_),
    .A2(_615_),
    .ZN(_616_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _866_ (
    .A1(_663_),
    .A2(_616_),
    .B(_522_),
    .ZN(_489_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _867_ (
    .A1(_506_),
    .A2(_616_),
    .ZN(_617_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _868_ (
    .A1(_505_),
    .A2(_615_),
    .B(_523_),
    .ZN(_618_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _869_ (
    .A1(_617_),
    .A2(_618_),
    .ZN(_488_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand4_1 _870_ (
    .A1(_506_),
    .A2(_505_),
    .A3(_523_),
    .A4(_615_),
    .ZN(_619_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _871_ (
    .A1(_503_),
    .A2(_502_),
    .B(_504_),
    .ZN(_620_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai31_1 _872_ (
    .A1(_522_),
    .A2(_615_),
    .A3(_620_),
    .B(_619_),
    .ZN(_487_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _873_ (
    .A1(_503_),
    .A2(_502_),
    .B(_522_),
    .ZN(_621_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _874_ (
    .A1(_503_),
    .A2(_502_),
    .B(_621_),
    .ZN(_622_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _875_ (
    .A1(_619_),
    .A2(_622_),
    .ZN(_486_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _876_ (
    .A1(_502_),
    .A2(_523_),
    .A3(_619_),
    .ZN(_485_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_1 _877_ (
    .I0(_669_),
    .I1(_668_),
    .S(_522_),
    .Z(_484_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_1 _878_ (
    .I0(_668_),
    .I1(_667_),
    .S(_522_),
    .Z(_483_)
  );
  gf180mcu_fd_sc_mcu7t5v0__or2_1 _879_ (
    .A1(_667_),
    .A2(_522_),
    .Z(_482_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _880_ (
    .A1(_702_),
    .A2(_517_),
    .ZN(_623_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _881_ (
    .A1(_703_),
    .A2(_580_),
    .A3(_623_),
    .ZN(_624_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _882_ (
    .A1(_702_),
    .A2(_517_),
    .ZN(_625_)
  );
  gf180mcu_fd_sc_mcu7t5v0__or2_1 _883_ (
    .A1(_702_),
    .A2(_517_),
    .Z(_626_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _884_ (
    .A1(_700_),
    .A2(_625_),
    .ZN(_627_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _885_ (
    .A1(_699_),
    .A2(_627_),
    .ZN(_628_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _886_ (
    .A1(_703_),
    .A2(_699_),
    .A3(_627_),
    .ZN(_629_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _887_ (
    .A1(_525_),
    .A2(_582_),
    .ZN(_672_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi211_1 _888_ (
    .A1(_701_),
    .A2(_580_),
    .B(_703_),
    .C(_702_),
    .ZN(_630_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _889_ (
    .I(_630_),
    .ZN(_695_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _890_ (
    .A1(_518_),
    .A2(_699_),
    .ZN(_631_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _891_ (
    .A1(_703_),
    .A2(_626_),
    .A3(_631_),
    .ZN(_632_)
  );
  gf180mcu_fd_sc_mcu7t5v0__or2_1 _892_ (
    .A1(_630_),
    .A2(_632_),
    .Z(_633_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _893_ (
    .I(_633_),
    .ZN(_674_)
  );
  gf180mcu_fd_sc_mcu7t5v0__or2_1 _894_ (
    .A1(_629_),
    .A2(_633_),
    .Z(_634_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _895_ (
    .I(_634_),
    .ZN(_692_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _896_ (
    .A1(_703_),
    .A2(_525_),
    .A3(_626_),
    .ZN(_635_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _897_ (
    .A1(_634_),
    .A2(_635_),
    .ZN(_689_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _898_ (
    .A1(_624_),
    .A2(_635_),
    .ZN(_636_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _899_ (
    .A1(_692_),
    .A2(_636_),
    .ZN(_637_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _900_ (
    .I(_637_),
    .ZN(_696_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _901_ (
    .A1(_703_),
    .A2(_579_),
    .A3(_623_),
    .ZN(_638_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _902_ (
    .A1(_637_),
    .A2(_638_),
    .ZN(_682_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _903_ (
    .A1(_703_),
    .A2(_623_),
    .A3(_631_),
    .ZN(_639_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _904_ (
    .A1(_637_),
    .A2(_639_),
    .ZN(_691_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _905_ (
    .A1(_518_),
    .A2(_582_),
    .ZN(_693_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _906_ (
    .A1(_703_),
    .A2(_524_),
    .ZN(_640_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi211_1 _907_ (
    .A1(_579_),
    .A2(_640_),
    .B(_638_),
    .C(_637_),
    .ZN(_694_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _908_ (
    .A1(_525_),
    .A2(_638_),
    .ZN(_641_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _909_ (
    .I(_641_),
    .ZN(_642_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _910_ (
    .A1(_637_),
    .A2(_642_),
    .ZN(_673_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _911_ (
    .A1(_518_),
    .A2(_699_),
    .A3(_640_),
    .ZN(_643_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _912_ (
    .A1(_703_),
    .A2(_525_),
    .A3(_623_),
    .ZN(_644_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _913_ (
    .A1(_579_),
    .A2(_640_),
    .B(_644_),
    .ZN(_645_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand4_1 _914_ (
    .A1(_636_),
    .A2(_641_),
    .A3(_643_),
    .A4(_645_),
    .ZN(_646_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _915_ (
    .A1(_634_),
    .A2(_646_),
    .ZN(_675_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _916_ (
    .A1(_703_),
    .A2(_581_),
    .ZN(_647_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _917_ (
    .A1(_525_),
    .A2(_647_),
    .ZN(_648_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _918_ (
    .A1(_518_),
    .A2(_647_),
    .ZN(_649_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _919_ (
    .A1(_518_),
    .A2(_640_),
    .B(_649_),
    .ZN(_650_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _920_ (
    .A1(_699_),
    .A2(_647_),
    .B(_650_),
    .ZN(_651_)
  );
  gf180mcu_fd_sc_mcu7t5v0__or2_1 _921_ (
    .A1(_646_),
    .A2(_651_),
    .Z(_652_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _922_ (
    .A1(_634_),
    .A2(_652_),
    .ZN(_688_)
  );
  gf180mcu_fd_sc_mcu7t5v0__or2_1 _923_ (
    .A1(_648_),
    .A2(_652_),
    .Z(_653_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _924_ (
    .A1(_634_),
    .A2(_653_),
    .ZN(_680_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _925_ (
    .A1(_703_),
    .A2(_625_),
    .ZN(_654_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _926_ (
    .A1(_680_),
    .A2(_654_),
    .Z(_687_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand4_1 _927_ (
    .A1(_703_),
    .A2(_702_),
    .A3(_517_),
    .A4(_579_),
    .ZN(_655_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _928_ (
    .A1(_687_),
    .A2(_655_),
    .Z(_676_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _929_ (
    .A1(_580_),
    .A2(_626_),
    .B(_690_),
    .ZN(_656_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor4_1 _930_ (
    .A1(_629_),
    .A2(_632_),
    .A3(_653_),
    .A4(_656_),
    .ZN(_677_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _931_ (
    .A1(_579_),
    .A2(_581_),
    .B(_664_),
    .ZN(_678_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _932_ (
    .A1(_700_),
    .A2(_654_),
    .B(_674_),
    .ZN(_657_)
  );
  gf180mcu_fd_sc_mcu7t5v0__or2_1 _933_ (
    .A1(_653_),
    .A2(_657_),
    .Z(_658_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _934_ (
    .A1(_628_),
    .A2(_658_),
    .ZN(_679_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _935_ (
    .A1(_524_),
    .A2(_525_),
    .B(_664_),
    .ZN(_681_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _936_ (
    .A1(_664_),
    .A2(_623_),
    .A3(_631_),
    .ZN(_659_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _937_ (
    .A1(_643_),
    .A2(_655_),
    .ZN(_660_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _938_ (
    .A1(_648_),
    .A2(_659_),
    .A3(_660_),
    .ZN(_661_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _939_ (
    .A1(_645_),
    .A2(_654_),
    .A3(_661_),
    .ZN(_662_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor4_1 _940_ (
    .A1(_637_),
    .A2(_642_),
    .A3(_651_),
    .A4(_662_),
    .ZN(_683_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _941_ (
    .A1(_675_),
    .A2(_650_),
    .Z(_684_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _942_ (
    .A1(_629_),
    .A2(_658_),
    .ZN(_685_)
  );
  gf180mcu_fd_sc_mcu7t5v0__buf_1 _943_ (
    .I(_703_),
    .Z(_686_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _944_ (
    .I(_670_),
    .ZN(_460_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _945_ (
    .I(_670_),
    .ZN(_461_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _946_ (
    .I(_670_),
    .ZN(_462_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _947_ (
    .I(_670_),
    .ZN(_463_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _948_ (
    .I(_670_),
    .ZN(_464_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _949_ (
    .I(_670_),
    .ZN(_465_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _950_ (
    .I(_670_),
    .ZN(_466_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _951_ (
    .I(_670_),
    .ZN(_467_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _952_ (
    .I(_670_),
    .ZN(_468_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _953_ (
    .I(_670_),
    .ZN(_469_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _954_ (
    .I(_670_),
    .ZN(_470_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _955_ (
    .I(_670_),
    .ZN(_471_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _956_ (
    .I(_670_),
    .ZN(_472_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _957_ (
    .I(_670_),
    .ZN(_473_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _958_ (
    .I(_670_),
    .ZN(_474_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _959_ (
    .I(_670_),
    .ZN(_475_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _960_ (
    .I(_670_),
    .ZN(_476_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _961_ (
    .I(_670_),
    .ZN(_477_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _962_ (
    .I(_670_),
    .ZN(_478_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _963_ (
    .I(_670_),
    .ZN(_479_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _964_ (
    .I(_670_),
    .ZN(_480_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _965_ (
    .I(_670_),
    .ZN(_481_)
  );
  (* src = "RTL/digital_pll_controller.v:100.5-133.8" *)
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _966_ (
    .CLK(clock),
    .D(osc),
    .Q(oscbuf[0]),
    .RN(_706_)
  );
  (* src = "RTL/digital_pll_controller.v:100.5-133.8" *)
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _967_ (
    .CLK(clock),
    .D(oscbuf[0]),
    .Q(oscbuf[1]),
    .RN(_707_)
  );
  (* src = "RTL/digital_pll_controller.v:100.5-133.8" *)
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _968_ (
    .CLK(clock),
    .D(oscbuf[1]),
    .Q(oscbuf[2]),
    .RN(_708_)
  );
  (* src = "RTL/digital_pll_controller.v:100.5-133.8" *)
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _969_ (
    .CLK(clock),
    .D(_729_),
    .Q(prep[0]),
    .RN(_709_)
  );
  (* src = "RTL/digital_pll_controller.v:100.5-133.8" *)
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _970_ (
    .CLK(clock),
    .D(_730_),
    .Q(prep[1]),
    .RN(_710_)
  );
  (* src = "RTL/digital_pll_controller.v:100.5-133.8" *)
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _971_ (
    .CLK(clock),
    .D(_731_),
    .Q(prep[2]),
    .RN(_711_)
  );
  (* src = "RTL/digital_pll_controller.v:100.5-133.8" *)
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _972_ (
    .CLK(clock),
    .D(_732_),
    .Q(count0[0]),
    .RN(_712_)
  );
  (* src = "RTL/digital_pll_controller.v:100.5-133.8" *)
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _973_ (
    .CLK(clock),
    .D(_733_),
    .Q(count0[1]),
    .RN(_713_)
  );
  (* src = "RTL/digital_pll_controller.v:100.5-133.8" *)
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _974_ (
    .CLK(clock),
    .D(_734_),
    .Q(count0[2]),
    .RN(_714_)
  );
  (* src = "RTL/digital_pll_controller.v:100.5-133.8" *)
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _975_ (
    .CLK(clock),
    .D(_735_),
    .Q(count0[3]),
    .RN(_715_)
  );
  (* src = "RTL/digital_pll_controller.v:100.5-133.8" *)
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _976_ (
    .CLK(clock),
    .D(_736_),
    .Q(count0[4]),
    .RN(_716_)
  );
  (* src = "RTL/digital_pll_controller.v:100.5-133.8" *)
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _977_ (
    .CLK(clock),
    .D(_737_),
    .Q(tval[0]),
    .RN(_717_)
  );
  (* src = "RTL/digital_pll_controller.v:100.5-133.8" *)
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _978_ (
    .CLK(clock),
    .D(_738_),
    .Q(tval[1]),
    .RN(_718_)
  );
  (* src = "RTL/digital_pll_controller.v:100.5-133.8" *)
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _979_ (
    .CLK(clock),
    .D(_739_),
    .Q(tval[2]),
    .RN(_719_)
  );
  (* src = "RTL/digital_pll_controller.v:100.5-133.8" *)
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _980_ (
    .CLK(clock),
    .D(_740_),
    .Q(tval[3]),
    .RN(_720_)
  );
  (* src = "RTL/digital_pll_controller.v:100.5-133.8" *)
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _981_ (
    .CLK(clock),
    .D(_741_),
    .Q(tval[4]),
    .RN(_721_)
  );
  (* src = "RTL/digital_pll_controller.v:100.5-133.8" *)
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _982_ (
    .CLK(clock),
    .D(_742_),
    .Q(tval[5]),
    .RN(_722_)
  );
  (* src = "RTL/digital_pll_controller.v:100.5-133.8" *)
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _983_ (
    .CLK(clock),
    .D(_743_),
    .Q(tval[6]),
    .RN(_723_)
  );
  (* src = "RTL/digital_pll_controller.v:100.5-133.8" *)
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _984_ (
    .CLK(clock),
    .D(_744_),
    .Q(count1[0]),
    .RN(_724_)
  );
  (* src = "RTL/digital_pll_controller.v:100.5-133.8" *)
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _985_ (
    .CLK(clock),
    .D(_745_),
    .Q(count1[1]),
    .RN(_725_)
  );
  (* src = "RTL/digital_pll_controller.v:100.5-133.8" *)
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _986_ (
    .CLK(clock),
    .D(_746_),
    .Q(count1[2]),
    .RN(_726_)
  );
  (* src = "RTL/digital_pll_controller.v:100.5-133.8" *)
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _987_ (
    .CLK(clock),
    .D(_747_),
    .Q(count1[3]),
    .RN(_727_)
  );
  (* src = "RTL/digital_pll_controller.v:100.5-133.8" *)
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _988_ (
    .CLK(clock),
    .D(_748_),
    .Q(count1[4]),
    .RN(_728_)
  );
  assign _705_[0] = _704_[0];
  assign tint = tval[6:2];
  assign _506_ = count0[4];
  assign _511_ = count1[4];
  assign _748_ = _501_;
  assign _505_ = count0[3];
  assign _510_ = count1[3];
  assign _747_ = _500_;
  assign _504_ = count0[2];
  assign _509_ = count1[2];
  assign _746_ = _499_;
  assign _503_ = count0[1];
  assign _508_ = count1[1];
  assign _745_ = _498_;
  assign _502_ = count0[0];
  assign _507_ = count1[0];
  assign _744_ = _497_;
  assign _703_ = tval[6];
  assign _743_ = _496_;
  assign _702_ = tval[5];
  assign _742_ = _495_;
  assign _701_ = tval[4];
  assign _741_ = _494_;
  assign _700_ = tval[3];
  assign _740_ = _493_;
  assign _699_ = tval[2];
  assign _739_ = _492_;
  assign _698_ = tval[1];
  assign _738_ = _491_;
  assign _697_ = tval[0];
  assign _737_ = _490_;
  assign _736_ = _489_;
  assign _735_ = _488_;
  assign _734_ = _487_;
  assign _733_ = _486_;
  assign _732_ = _485_;
  assign _668_ = prep[1];
  assign _669_ = prep[2];
  assign _731_ = _484_;
  assign _667_ = prep[0];
  assign _730_ = _483_;
  assign _729_ = _482_;
  assign _665_ = oscbuf[1];
  assign _666_ = oscbuf[2];
  assign _516_ = div[4];
  assign _515_ = div[3];
  assign _514_ = div[2];
  assign _513_ = div[1];
  assign _512_ = div[0];
  assign trim[0] = _671_;
  assign trim[1] = _682_;
  assign trim[2] = _689_;
  assign trim[3] = _690_;
  assign trim[4] = _691_;
  assign trim[5] = _692_;
  assign trim[6] = _693_;
  assign trim[7] = _694_;
  assign trim[8] = _695_;
  assign trim[9] = _696_;
  assign trim[10] = _672_;
  assign trim[11] = _673_;
  assign trim[12] = _674_;
  assign trim[13] = _675_;
  assign trim[14] = _676_;
  assign trim[15] = _677_;
  assign trim[16] = _678_;
  assign trim[17] = _679_;
  assign trim[18] = _680_;
  assign trim[19] = _681_;
  assign trim[20] = _683_;
  assign trim[21] = _684_;
  assign trim[22] = _685_;
  assign trim[23] = _686_;
  assign trim[24] = _687_;
  assign trim[25] = _688_;
  assign _670_ = reset;
  assign _706_ = _459_;
  assign _707_ = _460_;
  assign _708_ = _461_;
  assign _709_ = _462_;
  assign _710_ = _463_;
  assign _711_ = _464_;
  assign _712_ = _465_;
  assign _713_ = _466_;
  assign _714_ = _467_;
  assign _715_ = _468_;
  assign _716_ = _469_;
  assign _717_ = _470_;
  assign _718_ = _471_;
  assign _719_ = _472_;
  assign _720_ = _473_;
  assign _721_ = _474_;
  assign _722_ = _475_;
  assign _723_ = _476_;
  assign _724_ = _477_;
  assign _725_ = _478_;
  assign _726_ = _479_;
  assign _727_ = _480_;
  assign _728_ = _481_;
endmodule

(* src = "RTL/ring_osc2x13.v:161.1-265.10" *)
module ring_osc(reset, trim, clockp);
  (* src = "RTL/ring_osc2x13.v:220.16-220.17" *)
  wire [1:0] c;
  (* src = "RTL/ring_osc2x13.v:164.17-164.23" *)
  output [1:0] clockp;
  wire [1:0] clockp;
  (* src = "RTL/ring_osc2x13.v:219.17-219.18" *)
  wire [12:0] d;
  (* src = "RTL/ring_osc2x13.v:162.11-162.16" *)
  input reset;
  wire reset;
  (* src = "RTL/ring_osc2x13.v:163.18-163.22" *)
  input [25:0] trim;
  wire [25:0] trim;
  (* module_not_derived = 32'd1 *)
  (* src = "RTL/ring_osc2x13.v:227.18-231.7" *)
  delay_stage \dstage[0].id  (
    .in(d[0]),
    .out(d[1]),
    .trim({ trim[13], trim[0] })
  );
  (* module_not_derived = 32'd1 *)
  (* src = "RTL/ring_osc2x13.v:227.18-231.7" *)
  delay_stage \dstage[10].id  (
    .in(d[10]),
    .out(d[11]),
    .trim({ trim[23], trim[10] })
  );
  (* module_not_derived = 32'd1 *)
  (* src = "RTL/ring_osc2x13.v:227.18-231.7" *)
  delay_stage \dstage[11].id  (
    .in(d[11]),
    .out(d[12]),
    .trim({ trim[24], trim[11] })
  );
  (* module_not_derived = 32'd1 *)
  (* src = "RTL/ring_osc2x13.v:227.18-231.7" *)
  delay_stage \dstage[1].id  (
    .in(d[1]),
    .out(d[2]),
    .trim({ trim[14], trim[1] })
  );
  (* module_not_derived = 32'd1 *)
  (* src = "RTL/ring_osc2x13.v:227.18-231.7" *)
  delay_stage \dstage[2].id  (
    .in(d[2]),
    .out(d[3]),
    .trim({ trim[15], trim[2] })
  );
  (* module_not_derived = 32'd1 *)
  (* src = "RTL/ring_osc2x13.v:227.18-231.7" *)
  delay_stage \dstage[3].id  (
    .in(d[3]),
    .out(d[4]),
    .trim({ trim[16], trim[3] })
  );
  (* module_not_derived = 32'd1 *)
  (* src = "RTL/ring_osc2x13.v:227.18-231.7" *)
  delay_stage \dstage[4].id  (
    .in(d[4]),
    .out(d[5]),
    .trim({ trim[17], trim[4] })
  );
  (* module_not_derived = 32'd1 *)
  (* src = "RTL/ring_osc2x13.v:227.18-231.7" *)
  delay_stage \dstage[5].id  (
    .in(d[5]),
    .out(d[6]),
    .trim({ trim[18], trim[5] })
  );
  (* module_not_derived = 32'd1 *)
  (* src = "RTL/ring_osc2x13.v:227.18-231.7" *)
  delay_stage \dstage[6].id  (
    .in(d[6]),
    .out(d[7]),
    .trim({ trim[19], trim[6] })
  );
  (* module_not_derived = 32'd1 *)
  (* src = "RTL/ring_osc2x13.v:227.18-231.7" *)
  delay_stage \dstage[7].id  (
    .in(d[7]),
    .out(d[8]),
    .trim({ trim[20], trim[7] })
  );
  (* module_not_derived = 32'd1 *)
  (* src = "RTL/ring_osc2x13.v:227.18-231.7" *)
  delay_stage \dstage[8].id  (
    .in(d[8]),
    .out(d[9]),
    .trim({ trim[21], trim[8] })
  );
  (* module_not_derived = 32'd1 *)
  (* src = "RTL/ring_osc2x13.v:227.18-231.7" *)
  delay_stage \dstage[9].id  (
    .in(d[9]),
    .out(d[10]),
    .trim({ trim[22], trim[9] })
  );
  (* module_not_derived = 32'd1 *)
  (* src = "RTL/ring_osc2x13.v:246.39-249.6" *)
  gf180mcu_fd_sc_mcu7t5v0__clkinv_2 ibufp00 (
    .I(d[0]),
    .ZN(c[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "RTL/ring_osc2x13.v:250.39-253.6" *)
  gf180mcu_fd_sc_mcu7t5v0__clkinv_8 ibufp01 (
    .I(c[0]),
    .ZN(clockp[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "RTL/ring_osc2x13.v:254.39-257.6" *)
  gf180mcu_fd_sc_mcu7t5v0__clkinv_2 ibufp10 (
    .I(d[6]),
    .ZN(c[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "RTL/ring_osc2x13.v:258.39-261.6" *)
  gf180mcu_fd_sc_mcu7t5v0__clkinv_8 ibufp11 (
    .I(c[1]),
    .ZN(clockp[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "RTL/ring_osc2x13.v:237.17-242.6" *)
  start_stage iss (
    .in(d[12]),
    .out(d[0]),
    .reset(reset),
    .trim({ trim[25], trim[12] })
  );
endmodule

(* src = "RTL/ring_osc2x13.v:81.1-145.10" *)
module start_stage(in, trim, reset, out);
  (* src = "RTL/ring_osc2x13.v:87.22-87.28" *)
  wire ctrl0b;
  (* src = "RTL/ring_osc2x13.v:87.10-87.12" *)
  wire d0;
  (* src = "RTL/ring_osc2x13.v:87.14-87.16" *)
  wire d1;
  (* src = "RTL/ring_osc2x13.v:87.18-87.20" *)
  wire d2;
  (* src = "RTL/ring_osc2x13.v:82.11-82.13" *)
  input in;
  wire in;
  (* src = "RTL/ring_osc2x13.v:87.30-87.33" *)
  wire one;
  (* src = "RTL/ring_osc2x13.v:85.12-85.15" *)
  output out;
  wire out;
  (* src = "RTL/ring_osc2x13.v:84.11-84.16" *)
  input reset;
  wire reset;
  (* src = "RTL/ring_osc2x13.v:83.17-83.21" *)
  input [1:0] trim;
  wire [1:0] trim;
  (* src = "RTL/ring_osc2x13.v:88.10-88.16" *)
  wire trim1b;
  (* module_not_derived = 32'd1 *)
  (* src = "RTL/ring_osc2x13.v:141.35-143.6" *)
  gf180mcu_fd_sc_mcu7t5v0__tieh const1 (
    .Z(one)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "RTL/ring_osc2x13.v:135.37-139.6" *)
  gf180mcu_fd_sc_mcu7t5v0__nor2_2 ctrlen0 (
    .A1(reset),
    .A2(trim[0]),
    .ZN(ctrl0b)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "RTL/ring_osc2x13.v:95.39-98.6" *)
  gf180mcu_fd_sc_mcu7t5v0__clkbuf_1 delaybuf0 (
    .I(in),
    .Z(d0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "RTL/ring_osc2x13.v:117.37-121.6" *)
  gf180mcu_fd_sc_mcu7t5v0__invz_2 delayen0 (
    .EN(trim[0]),
    .I(d2),
    .ZN(out)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "RTL/ring_osc2x13.v:100.37-104.6" *)
  gf180mcu_fd_sc_mcu7t5v0__invz_2 delayen1 (
    .EN(trim[1]),
    .I(d0),
    .ZN(d1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "RTL/ring_osc2x13.v:123.37-127.6" *)
  gf180mcu_fd_sc_mcu7t5v0__invz_8 delayenb0 (
    .EN(ctrl0b),
    .I(in),
    .ZN(out)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "RTL/ring_osc2x13.v:106.37-110.6" *)
  gf180mcu_fd_sc_mcu7t5v0__invz_4 delayenb1 (
    .EN(trim1b),
    .I(in),
    .ZN(d1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "RTL/ring_osc2x13.v:112.39-115.6" *)
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 delayint0 (
    .I(d1),
    .ZN(d2)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "RTL/ring_osc2x13.v:129.37-133.6" *)
  gf180mcu_fd_sc_mcu7t5v0__invz_1 reseten0 (
    .EN(reset),
    .I(one),
    .ZN(out)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "RTL/ring_osc2x13.v:90.36-93.6" *)
  gf180mcu_fd_sc_mcu7t5v0__inv_1 trim1bar (
    .I(trim[1]),
    .ZN(trim1b)
  );
endmodule
